!unquoted procedure System($alias, $label, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
rectangle "$getSystem($label, $descr, $sprite)" <<system>> as $alias
!endprocedure

!unquoted procedure System_Ext($alias, $label, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
rectangle "$getSystem($label, $descr, $sprite)" <<external_system>> as $alias
!endprocedure

!unquoted procedure Rel($from, $to, $label)
!$key_from = "present-" + $from
!$exists_from = %variable_exists($key_from)
!$key_to = "present-" + $to
!$exists_to = %variable_exists($key_to)
!$direction = "-->>"

!if ($exists_from == "1") && ($exists_to == "1")
$from $direction $to: **$label**
!endif
!endprocedure

!unquoted procedure Rel($from, $to, $label, $techn)
!$key_from = "present-" + $from
!$exists_from = %variable_exists($key_from)
!$key_to = "present-" + $to
!$exists_to = %variable_exists($key_to)
!$direction = "-->>"

!if ($exists_from == "1") && ($exists_to == "1")
$from $direction $to: **$label**\n//<size:$TECHN_FONT_SIZE>[$techn]</size>//
!endif
!endprocedure

!unquoted procedure Person($alias, $label, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
rectangle "$getPerson($label, $descr, $sprite)" <<person>> as $alias
!endprocedure

!unquoted procedure NSXContainer($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
rectangle "$getContainer($label, $techn, $descr, $sprite)" <<container>> as $alias
!endprocedure

!unquoted procedure NSXContainerDb($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
database "$getContainer($label, $techn, $descr, $sprite)" <<container>> as $alias
!endprocedure

!unquoted procedure NSXContainerQueue($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
queue "$getContainer($label, $techn, $descr, $sprite)" <<container>> as $alias
!endprocedure

!unquoted procedure NSXContainer_Ext($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
rectangle "$getContainer($label, $techn, $descr, $sprite)" <<external_container>> as $alias
!endprocedure

!unquoted procedure NSXContainerDb_Ext($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
database "$getContainer($label, $techn, $descr, $sprite)" <<external_container>> as $alias
!endprocedure

!unquoted procedure NSXContainerQueue_Ext($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
queue "$getContainer($label, $techn, $descr, $sprite)" <<external_container>> as $alias
!endprocedure

!unquoted function Enterprise_Boundary($alias, $label)
!$key = "present-" + $alias
%set_variable_value($key, "1")
!return Boundary($alias, $label, "Enterprise")
!endfunction

!unquoted function System_Boundary($alias, $label)
!$key = "present-" + $alias
%set_variable_value($key, "1")
!return Boundary($alias, $label, "System")
!endfunction

!unquoted function Container_Boundary($alias, $label)
!$key = "present-" + $alias
%set_variable_value($key, "1")
!return Boundary($alias, $label, "Container")
!endfunction

!unquoted procedure NSXComponent($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
rectangle "$getComponent($label, $techn, $descr, $sprite)" <<component>> as $alias
!endprocedure

!unquoted procedure NSXComponentDb($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
database "$getComponent($label, $techn, $descr, $sprite)" <<component>> as $alias
!endprocedure

!unquoted procedure NSXComponentQueue($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
queue "$getComponent($label, $techn, $descr, $sprite)" <<component>> as $alias
!endprocedure

!unquoted procedure NSXComponent_Ext($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
rectangle "$getComponent($label, $techn, $descr, $sprite)" <<external_component>> as $alias
!endprocedure

!unquoted procedure NSXComponentDb_Ext($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
database "$getComponent($label, $techn, $descr, $sprite)" <<external_component>> as $alias
!endprocedure

!unquoted procedure NSXComponentQueue_Ext($alias, $label, $techn, $descr="", $sprite="")
!$key = "present-" + $alias
%set_variable_value($key, "1")
queue "$getComponent($label, $techn, $descr, $sprite)" <<external_component>> as $alias
!endprocedure
